'use client';
import {useState,useId,type ReactNode} from 'react';
import Link from './navigation';
import {ShieldCheck,ArrowLeft,ArrowRight,UploadCloud,FileText,X,Loader2,Info,Search,FolderOpen,CheckCircle2} from 'lucide-react';
import {Select,SelectTrigger,SelectContent,SelectItem,SelectValue} from '@/components/ui/select';
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription,EmptyMedia} from '@/components/ui/empty';
import {Skeleton} from '@/components/ui/skeleton';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Progress} from '@/components/ui/progress';
import {toast} from 'sonner';
import {api} from '@/lib/api';
import {statusLabels,statusColors,requestNumber,riskLabels,type RequestStatus,type Risk,type DocumentRecord,type LegalRequest} from '@/lib/models';
export function Brand({light=false}:{light?:boolean}){return <Link className={'brand'+(!light?' public':'')} href="/"><span className="brand-icon"><ShieldCheck size={27}/></span><span>مرصاد<small>قرارات أوضح. مخاطر أقل.</small></span></Link>}
export function Btn({children,href,kind='',busy=false,...props}:{children:ReactNode;href?:string;kind?:string;busy?:boolean}&React.ButtonHTMLAttributes<HTMLButtonElement>){const cls='btn '+kind;if(href)return <Link href={href} className={cls}>{children}</Link>;return <button {...props} disabled={busy||props.disabled} className={cls}>{busy&&<Loader2 size={17} className="animate-spin"/>}{children}</button>}
export function Heading({title,description,children,kicker}:{title:string;description?:string;children?:ReactNode;kicker?:string}){return <div className="page-heading"><div>{kicker&&<div className="kicker">{kicker}</div>}<h1>{title}</h1>{description&&<p>{description}</p>}</div>{children&&<div className="actions">{children}</div>}</div>}
export function Badge({children,color=''}:{children:ReactNode;color?:string}){return <span className={'badge '+color}>{children}</span>}
export function Status({value}:{value:RequestStatus}){return <Badge color={statusColors[value]}>{statusLabels[value]}</Badge>}
export function RiskBadge({value}:{value:Risk}){return <Badge color={statusColors[value]}>{riskLabels[value]}</Badge>}
export function Panel({title,subtitle,action,children,className=''}:{title?:string;subtitle?:string;action?:ReactNode;children:ReactNode;className?:string}){return <section className={'panel '+className}>{title&&<div className="panel-head"><div><h2>{title}</h2>{subtitle&&<p className="panel-sub">{subtitle}</p>}</div>{action}</div>}{children}</section>}
export function TextLink({href,children}:{href:string;children:ReactNode}){return <Link className="text-link" href={href}>{children}<ArrowLeft size={15}/></Link>}
export function Back({href,children='رجوع'}:{href:string;children?:ReactNode}){return <Link href={href} className="back-link"><ArrowRight size={15}/>{children}</Link>}
export function Input({label,required=false,full=false,hint,...props}:{label:string;full?:boolean;hint?:string}&React.InputHTMLAttributes<HTMLInputElement>){const id=useId();return <label className={'field '+(full?'full':'')} htmlFor={id}><span>{label}{required&&<span className="required">*</span>}</span><input {...props} required={required} id={id} className="input"/>{hint&&<small>{hint}</small>}</label>}
export function Textarea({label,required=false,full=false,...props}:{label:string;full?:boolean}&React.TextareaHTMLAttributes<HTMLTextAreaElement>){const id=useId();return <label className={'field '+(full?'full':'')} htmlFor={id}><span>{label}{required&&<span className="required">*</span>}</span><textarea {...props} required={required} id={id} className="input"/></label>}
export function Choice({label,value,onChange,options,placeholder='اختر',required=false}:{label?:string;value:string;onChange:(s:string)=>void;options:(string|{value:string;label:string})[];placeholder?:string;required?:boolean}){const id=useId();return <div className="field">{label&&<label htmlFor={id}>{label}{required&&<span className="required">*</span>}</label>}<Select dir="rtl" value={value} onValueChange={onChange} required={required}><SelectTrigger id={id} aria-label={label||placeholder}><SelectValue placeholder={placeholder}/></SelectTrigger><SelectContent position="popper" align="end">{options.map(o=>{const v=typeof o==='string'?o:o.value;return <SelectItem key={v} value={v}>{typeof o==='string'?o:o.label}</SelectItem>})}</SelectContent></Select></div>}
export function SearchBox({value,onChange,placeholder='ابحث...'}:{value:string;onChange:(s:string)=>void;placeholder?:string}){return <div className="search"><Search size={17}/><input className="input" aria-label={placeholder} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></div>}
export function Notice({children}:{children:ReactNode}){return <div className="info-note"><Info size={17}/><span>{children}</span></div>}
export function ErrorBox({error}:{error:string}){return error?<div className="error-box" role="alert">{error}</div>:null}
export function EmptyState({title='لا توجد سجلات بعد',description,children}:{title?:string;description?:string;children?:ReactNode}){return <Empty><EmptyHeader><EmptyMedia variant="icon"><FolderOpen/></EmptyMedia><EmptyTitle>{title}</EmptyTitle>{description&&<EmptyDescription>{description}</EmptyDescription>}</EmptyHeader>{children}</Empty>}
export function Loading(){return <div className="loading-screen" aria-label="جارٍ التحميل"><Skeleton className="h-9 w-2/5"/><div className="stats">{[1,2,3,4].map(n=><Skeleton key={n} className="h-36"/>)}</div><Skeleton className="h-64 w-full"/></div>}
export const date=(s:string)=>new Date(s).toLocaleDateString('ar-SA',{year:'numeric',month:'short',day:'numeric',calendar:'gregory'});
export function Stepper({step=1}:{step?:number}){return <div className="stepper">{['بيانات الحالة','نتيجة التحليل','المراجعة القانونية'].map((v,i)=><span key={v} className={step===i+1?'current':''}><b className="step-number">{i+1}</b>{v}{i<2&&<ArrowLeft size={13}/>}</span>)}</div>}
export function Processing(){return <div className="panel processing" role="status"><div className="processing-mark"><ShieldCheck size={40}/></div><h2>نجهّز نتيجة حالتك</h2><p>حفظ المعلومات وتجهيز النتيجة التجريبية</p><Progress value={65} aria-label="تجهيز النتيجة"/><small>تستند هذه التجربة إلى سيناريوهات معدّة مسبقًا</small></div>}
export function Attachments({docs,remove}:{docs:DocumentRecord[];remove?:(id:string)=>void}){if(!docs.length)return null;return <div className="attachments">{docs.map(d=><div className="attachment" key={d.id}><FileText size={16}/><a href={'/api/files/'+d.id} target="_blank" rel="noreferrer"><span>{d.name}</span></a>{remove&&<button type="button" aria-label={'إزالة '+d.name+' من هذه الحالة'} onClick={()=>remove(d.id)}><X size={14}/></button>}</div>)}</div>}
export function Uploader({docs,onChange,employeeId,category='مستند',max=5,onBusy}:{docs:DocumentRecord[];onChange:(d:DocumentRecord[])=>void;employeeId?:string;category?:string;max?:number;onBusy?:(b:boolean)=>void}){const [busy,setBusy]=useState(false);const [error,setError]=useState('');async function upload(files:FileList|null){if(!files)return;if(docs.length+files.length>max){setError(`الحد الأقصى ${max} ملفات.`);return}setBusy(true);onBusy?.(true);setError('');const next=[...docs];try{for(const file of Array.from(files)){if(file.size>10*1024*1024)throw new Error('حجم الملف يتجاوز 10MB.');const f=new FormData();f.append('file',file);f.append('category',category);if(employeeId)f.append('employee_id',employeeId);const d=await api<DocumentRecord>('documents',{method:'POST',body:f});next.push(d);onChange([...next]);}toast.success('تم حفظ المستندات')}catch(e){setError((e as Error).message)}finally{setBusy(false);onBusy?.(false)}}return <div><label className="upload-area" tabIndex={0} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();e.currentTarget.querySelector('input')?.click()}}}>{busy?<Loader2 className="animate-spin" size={28}/>:<UploadCloud size={28}/>}<strong>{busy?'جارٍ حفظ المستند...':'اختر مستندًا من جهازك'}</strong><small>PDF أو Word • حتى 10MB للملف • {max} مرفقات كحد أقصى</small><input type="file" multiple={max>1} accept=".pdf,.doc,.docx" disabled={busy||docs.length>=max} onChange={e=>{upload(e.target.files);e.target.value=''}} aria-label="رفع المستندات"/></label><Attachments docs={docs} remove={employeeId?undefined:id=>onChange(docs.filter(d=>d.id!==id))}/><ErrorBox error={error}/></div>}
export function RequestsTable({items,prefix='/app',showCompany=false}:{items:LegalRequest[];prefix?:string;showCompany?:boolean}){if(!items.length)return <EmptyState title="لا توجد طلبات هنا" description="ستظهر الطلبات فور إرسالها."/>;return <><div className="desktop-table"><Table><TableHeader><TableRow><TableHead>الطلب</TableHead>{showCompany&&<TableHead>الشركة</TableHead>}<TableHead>الحالة</TableHead><TableHead>التاريخ</TableHead><TableHead>الإجراء</TableHead></TableRow></TableHeader><TableBody>{items.map(r=><TableRow key={r.id}><TableCell><span className="table-title">{r.type}</span><span className="table-sub ltr">{requestNumber(r)}</span></TableCell>{showCompany&&<TableCell>{r.company_name}</TableCell>}<TableCell><Status value={r.status}/></TableCell><TableCell><span className="muted" style={{fontSize:12}}>{date(r.created_at)}</span></TableCell><TableCell><TextLink href={`${prefix}/requests/${r.id}`}>{r.status==='waiting'&&prefix==='/app'?'استكمال الطلب':'عرض الطلب'}</TextLink></TableCell></TableRow>)}</TableBody></Table></div><div className="mobile-cards">{items.map(r=><div className="mobile-row" key={r.id}><div><h3>{r.type}</h3><p>{showCompany?r.company_name:requestNumber(r)}</p><TextLink href={`${prefix}/requests/${r.id}`}>عرض الطلب</TextLink></div><Status value={r.status}/></div>)}</div></>}
