import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {rawDb,first,rows,stmt,bucket,timestamp,newId} from '@/db/access';
import {analysisProvider} from './analysis';
import {serviceDuration} from './models';
import {demoPdfBase64} from './demo-asset';
import {z} from 'zod';

class ApiError extends Error{constructor(public status:number,message:string){super(message)}}
function fail(status:number,message:string):never{throw new ApiError(status,message)}
const json=(v:any,status=200,headers:Record<string,string>={})=>Response.json(v,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...headers}});
const idRule=z.string().uuid();
const short=z.string().trim().min(1).max(160);
const employeeRule=z.object({full_name:short,employee_number:z.string().trim().min(1).max(40),job_title:short,department:z.string().trim().max(120).default(''),email:z.union([z.string().email().max(160),z.literal('')]).default(''),start_date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),contract_type:z.enum(['محدد المدة','غير محدد المدة','غير معلوم']),contract_end:z.string().default(''),status:z.enum(['active','leave','ended']).default('active'),notes:z.string().trim().max(3000).default('')});
const fileIds=z.array(idRule).max(5).default([]);
const reqRule=z.object({id:idRule,analysis_id:idRule.nullable().optional(),type:short,description:z.string().trim().min(10).max(5000),urgency:z.enum(['عادي','عاجل','عاجل جدًا']),document_ids:fileIds});
async function body(req:Request){if(Number(req.headers.get('content-length')||0)>65000)fail(413,'البيانات أكبر من الحد المسموح.');const s=await req.text();if(s.length>65000)fail(413,'البيانات أكبر من الحد المسموح.');try{return JSON.parse(s)}catch{fail(400,'تعذر قراءة البيانات المرسلة.')}}
async function digest(s:string){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function cookieValue(req:Request){return req.headers.get('cookie')?.split(';').map(x=>x.trim()).find(x=>x.startsWith('mirsad_admin='))?.slice(13)||''}
async function isAdmin(req:Request,userId:string){const token=cookieValue(req);if(!token)return false;return !!await first('SELECT user_id FROM admin_sessions WHERE token_hash=? AND user_id=? AND expires_at>?',await digest(token),userId,Date.now())}
function sessionCookie(req:Request,token:string,age:number){return `mirsad_admin=${token}; HttpOnly; Path=/; SameSite=Lax; Max-Age=${age}${new URL(req.url).protocol==='https:'?'; Secure':''}`}
async function companyFor(userId:string){return first('SELECT c.* FROM companies c JOIN memberships m ON m.company_id=c.id WHERE m.user_id=?',userId)}
async function requireCompany(userId:string){return (await companyFor(userId))||fail(409,'أنشئ مساحة شركتك أولًا.');}
async function checkDocuments(ids:string[],companyId:string){const unique=[...new Set(ids)];if(unique.length>5)fail(400,'الحد الأقصى خمسة مرفقات.');for(const id of unique){if(!await first('SELECT id FROM documents WHERE id=? AND company_id=?',id,companyId))fail(403,'لا يمكن إرفاق ملف خارج مساحة شركتك.')}return unique}
function decodeAnalysis(a:any){const {inputs_json,result_json,...rest}=a;return {...rest,inputs:JSON.parse(inputs_json),result:JSON.parse(result_json)}}
async function requestDetail(id:string,companyId:string|null,admin:boolean){const r=await first('SELECT r.*,c.name company_name FROM legal_requests r JOIN companies c ON c.id=r.company_id WHERE r.id=?',id);if(!r||(!admin&&r.company_id!==companyId))fail(404,'الطلب غير موجود أو غير متاح لحسابك.');const docs=await rows('SELECT d.id,d.company_id,d.employee_id,d.name,d.mime,d.size,d.category,d.created_at FROM documents d JOIN request_documents rd ON rd.document_id=d.id WHERE rd.request_id=?',id);const events=await rows('SELECT id,request_id,actor_name,from_status,to_status,message,created_at FROM request_events WHERE request_id=? ORDER BY created_at ASC',id);let analysis=null;if(r.analysis_id){const a=await first('SELECT * FROM analyses WHERE id=? AND company_id=?',r.analysis_id,r.company_id);if(a)analysis=decodeAnalysis(a)}return {request:{...r,document_ids:docs.map((d:any)=>d.id)},documents:docs,events,analysis}}

async function createCompany(user:any,name:string,contact:string,sector:string,demo=false){const existing=await companyFor(user.userId);if(existing)return existing;const id=newId();await rawDb().batch([stmt('INSERT INTO companies (id,name,sector,contact_name,is_demo,created_at) VALUES (?,?,?,?,?,?)',id,name,sector,contact,demo?1:0,timestamp()),stmt('INSERT INTO memberships (user_id,company_id,display_name,email) VALUES (?,?,?,?)',user.userId,id,contact,user.email)]);return first('SELECT * FROM companies WHERE id=?',id)}
async function seedDemo(user:any){const company=await createCompany(user,'شركة المدار للتوريد','مسؤول الشركة','التجارة والتوريد',true);if(!company.is_demo)fail(409,'حسابك مرتبط بشركة فعلية؛ بيانات العرض لا تُضاف إليها.');if(await first('SELECT id FROM employees WHERE company_id=? LIMIT 1',company.id))return company;
 const c=company.id;const now=timestamp();const ids=[newId(),newId(),newId(),newId(),newId(),newId()];const specs=[['أحمد العتيبي','أخصائي مبيعات','المبيعات','2024-05-01','محدد المدة','2027-04-30','active'],['سارة القحطاني','مديرة الموارد البشرية','الموارد البشرية','2023-02-15','غير محدد المدة','','active'],['خالد الدوسري','محاسب','المالية','2022-09-01','غير محدد المدة','','active'],['ريم الحربي','منسقة مشتريات','المشتريات','2025-01-12','محدد المدة','2027-01-11','leave'],['عبدالله السبيعي','مسؤول تشغيل','العمليات','2023-07-01','غير محدد المدة','','active'],['نورة المطيري','أخصائية علاقات عملاء','خدمة العملاء','2024-11-01','محدد المدة','2027-10-31','active']];
 const seedStatements=specs.map((e,i)=>stmt('INSERT INTO employees (id,company_id,full_name,employee_number,job_title,department,email,start_date,contract_type,contract_end,status,notes,archived,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,0,?,?)',ids[i],c,e[0],`EMP-${101+i}`,e[1],e[2],'',e[3],e[4],e[5],e[6],'بيانات افتراضية مخصصة لعرض تجربة مرصاد.',now,now));
 const docIds=[newId(),newId(),newId()];const bytes=Uint8Array.from(atob(demoPdfBase64),ch=>ch.charCodeAt(0));
 for(let i=0;i<3;i++){const key=`${c}/${docIds[i]}.pdf`;await bucket().put(key,bytes,{httpMetadata:{contentType:'application/pdf'}});seedStatements.push(stmt('INSERT INTO documents (id,company_id,employee_id,storage_key,name,mime,size,category,uploaded_by,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)',docIds[i],c,i===0?ids[0]:null,key,['عقد-عمل-تجريبي.pdf','عقد-توريد-تجريبي.pdf','جدول-دفعات-تجريبي.pdf'][i],'application/pdf',bytes.length,i===0?'عقد موظف':i===1?'عقد':'مستند',user.userId,now));}
 const anaIds=[newId(),newId(),newId(),newId()];const inputs=[{employee_name:specs[0][0],reason:'ضعف أداء متكرر',contract_type:'محدد المدة',duration:serviceDuration(specs[0][3]),written:'نعم',dues:'نعم',warnings:'لا'},{supplier:'روافد للمواد التشغيلية',value:'240000',scope:'توريد مواد تشغيلية',payment:'50% دفعة مقدمة',duration:'12 شهرًا',delivery:'تسليم شهري',warranty:'غير محدد',termination:''},{title:'مراجعة عقد التوريد'},{reason:'تغيير هيكل الفريق',contract_type:'غير معلوم',written:'غير معلوم',dues:'غير معلوم',warnings:'غير معلوم'}] as Record<string,string>[];
 const scenarios=['termination','supplier','contract','termination'];const titles=['إنهاء علاقة موظف: أحمد العتيبي','توقيع عقد مع مورد','عقد توريد مواد تشغيلية','مراجعة قرار إعادة هيكلة'];
 const batch=[];for(let i=0;i<4;i++){const res=analysisProvider.analyze(scenarios[i],inputs[i],i<3?1:0);batch.push(stmt('INSERT INTO analyses (id,company_id,employee_id,kind,scenario,title,inputs_json,result_json,risk,engine,created_by,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)',anaIds[i],c,i===0?ids[0]:null,i===2?'contract':'decision',scenarios[i],titles[i],JSON.stringify(inputs[i]),JSON.stringify(res),res.risk,'demo-v1',user.userId,now));if(i<3)batch.push(stmt('INSERT INTO analysis_documents (analysis_id,document_id) VALUES (?,?)',anaIds[i],docIds[i===0?0:1]));}
 seedStatements.push(...batch);
 for(let i=0;i<3;i++){const id=newId();const statuses=['new','waiting','reviewing'];const message=i===1?'يرجى إرفاق جدول الدفعات المحدث وتوضيح موعد التسليم الأول.':i===2?'بدأ الفريق القانوني مراجعة ملف الحالة.':'تم استلام الطلب وإضافته إلى قائمة المراجعة.';seedStatements.push(stmt('INSERT INTO legal_requests (id,company_id,analysis_id,type,description,urgency,status,resolution,version,created_by,created_at,updated_at) VALUES (?,?,?,?,?,?,?,\'\',0,?,?,?)',id,c,anaIds[i],['مراجعة إنهاء علاقة موظف','مراجعة عقد مورد','مراجعة عقد توريد'][i],['نرغب في مراجعة القرار وتحديد المستحقات والمستندات اللازمة قبل اعتماده.','مراجعة الدفعة المقدمة والضمان وشروط التسليم في عقد المورد.','مراجعة التزامات الطرفين وشروط الإنهاء والتأخير.'][i],i===0?'عاجل':'عادي',statuses[i],user.userId,now,now),stmt('INSERT INTO request_documents (request_id,document_id) VALUES (?,?)',id,docIds[i===0?0:1]),stmt('INSERT INTO request_events (id,request_id,actor_id,actor_name,from_status,to_status,message,created_at) VALUES (?,?,?,?,?,?,?,?)',newId(),id,user.userId,'الفريق القانوني (بيانات عرض)','new',statuses[i],message,now));}
 await rawDb().batch(seedStatements);
 return company;
}

export async function handle(req:Request){try{
 const url=new URL(req.url);const path=url.pathname.replace(/^\/api\/?/,'').replace(/\/$/,'');const method=req.method;
 if(!['GET','HEAD'].includes(method)){const origin=req.headers.get('origin');const allowed=new Set([url.origin,(env as any).APP_ORIGIN].filter(Boolean));if((origin&&!allowed.has(origin))||req.headers.get('sec-fetch-site')==='cross-site')fail(403,'الطلب صادر من جهة غير مسموحة.')}
 const user=await getChatGPTUser();
 if(path==='me'){if(!user)return json({authenticated:false,company:null,isAdmin:false});return json({authenticated:true,displayName:user.displayName,email:user.email,company:await companyFor(user.userId),isAdmin:await isAdmin(req,user.userId)})}
 if(!user)fail(401,'سجّل الدخول للمتابعة.');
 const admin=await isAdmin(req,user.userId);
 if(path==='admin/login'&&method==='POST'){
  const data=z.object({code:z.string().min(1).max(200)}).parse(await body(req));const code=(env as any).ADMIN_ACCESS_CODE;
  if(!code)fail(503,'لم يُجهّز دخول الإدارة بعد.');
  const old=await first('SELECT * FROM admin_attempts WHERE user_id=?',user.userId);const now=Date.now();
  if(old&&old.window_start>now-900000&&old.failures>=6)fail(429,'محاولات كثيرة؛ أعد المحاولة بعد 15 دقيقة.');
  if(await digest(data.code)!==await digest(code)){await stmt('INSERT INTO admin_attempts (user_id,failures,window_start) VALUES (?,1,?) ON CONFLICT(user_id) DO UPDATE SET failures=CASE WHEN window_start<? THEN 1 ELSE failures+1 END,window_start=CASE WHEN window_start<? THEN excluded.window_start ELSE window_start END',user.userId,now,now-900000,now-900000).run();fail(403,'رمز دخول الإدارة غير صحيح.')}
  const token=newId()+newId();await rawDb().batch([stmt('INSERT INTO admin_sessions (token_hash,user_id,expires_at) VALUES (?,?,?)',await digest(token),user.userId,now+14400000),stmt('DELETE FROM admin_attempts WHERE user_id=?',user.userId),stmt('DELETE FROM admin_sessions WHERE expires_at<?',now)]);return json({ok:true},200,{'Set-Cookie':sessionCookie(req,token,14400)});
 }
 if(path==='admin/logout'&&method==='POST'){const token=cookieValue(req);if(token)await stmt('DELETE FROM admin_sessions WHERE token_hash=? AND user_id=?',await digest(token),user.userId).run();return json({ok:true},200,{'Set-Cookie':sessionCookie(req,'',0)})}
 if(path==='company'&&method==='POST'){const d=z.object({name:short,contact_name:short,sector:z.string().trim().max(120).default('')}).parse(await body(req));return json(await createCompany(user,d.name,d.contact_name,d.sector),201)}
 if(path==='demo'&&method==='POST')return json(await seedDemo(user));
 const company=await companyFor(user.userId);
 if(path==='data'&&method==='GET'){
  const all=url.searchParams.get('scope')==='admin';if(all&&!admin)fail(403,'هذه الصفحة مخصصة للإدارة.');if(!all&&!company)fail(409,'أنشئ مساحة شركتك أولًا.');const cid=company?.id;
  const args=all?[]:[cid];const scope=all?'':' WHERE t.company_id=?';
  const [employees,documents,aa,rr,companies,ad,rd]=await Promise.all([
   rows(`SELECT t.* FROM employees t${scope} ORDER BY t.created_at DESC`,...args),
   rows(`SELECT t.id,t.company_id,t.employee_id,t.name,t.mime,t.size,t.category,t.created_at,c.name company_name FROM documents t JOIN companies c ON c.id=t.company_id${scope} ORDER BY t.created_at DESC`,...args),
   rows(`SELECT t.*,c.name company_name FROM analyses t JOIN companies c ON c.id=t.company_id${scope} ORDER BY t.created_at DESC`,...args),
   rows(`SELECT t.*,c.name company_name FROM legal_requests t JOIN companies c ON c.id=t.company_id${scope} ORDER BY t.created_at DESC,t.seq DESC`,...args),
   all?rows('SELECT c.*,(SELECT COUNT(*) FROM employees e WHERE e.company_id=c.id AND e.archived=0) employee_count,(SELECT COUNT(*) FROM legal_requests r WHERE r.company_id=c.id) request_count FROM companies c ORDER BY c.created_at DESC'):Promise.resolve([]),
   rows(`SELECT ad.analysis_id,ad.document_id FROM analysis_documents ad JOIN analyses t ON t.id=ad.analysis_id${scope}`,...args),
   rows(`SELECT rd.request_id,rd.document_id FROM request_documents rd JOIN legal_requests t ON t.id=rd.request_id${scope}`,...args)]);
  return json({company,companies,employees,documents,analyses:aa.map((a:any)=>({...decodeAnalysis(a),document_ids:ad.filter((d:any)=>d.analysis_id===a.id).map((d:any)=>d.document_id)})),requests:rr.map((r:any)=>({...r,document_ids:rd.filter((d:any)=>d.request_id===r.id).map((d:any)=>d.document_id)}))});
 }
 if(path.startsWith('files/')&&method==='GET'){const id=path.split('/')[1];const d=await first('SELECT * FROM documents WHERE id=?',id);if(!d||(!admin&&d.company_id!==company?.id))fail(404,'الملف غير متاح لحسابك.');const o=await bucket().get(d.storage_key);if(!o)fail(404,'تعذر العثور على الملف.');return new Response(o.body,{headers:{'Content-Type':d.mime,'Content-Disposition':`${url.searchParams.get('download')||d.mime!=='application/pdf'?'attachment':'inline'}; filename="document.${d.name.split('.').pop()}"; filename*=UTF-8''${encodeURIComponent(d.name)}`,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"frame-ancestors 'self'"}})}
 if(path.startsWith('requests/')&&method==='GET')return json(await requestDetail(path.split('/')[1],company?.id,admin));
 if(path.startsWith('requests/')&&method==='PATCH'){
  const id=path.split('/')[1];const d=z.object({event_id:idRule,status:z.enum(['new','reviewing','waiting','reviewed','closed']),message:z.string().trim().max(5000).default(''),version:z.number().int().nonnegative(),document_ids:fileIds}).parse(await body(req));
  const {request:r}=await requestDetail(id,company?.id,admin);if(await first('SELECT id FROM request_events WHERE id=? AND request_id=?',d.event_id,id))return json({ok:true});
  if(!admin&&(r.status!=='waiting'||d.status!=='reviewing'))fail(403,'يمكنك الرد عندما يكون الطلب بانتظار معلومات.');
  const allowed:Record<string,string[]>={new:['reviewing'],reviewing:['waiting','reviewed'],waiting:['reviewing'],reviewed:['closed','reviewing'],closed:['reviewing']};if(!allowed[r.status]?.includes(d.status))fail(400,'هذا الانتقال غير متاح لحالة الطلب الحالية.');
  if((['waiting','reviewed'].includes(d.status)||r.status==='closed'||!admin)&&!d.message&&!d.document_ids.length)fail(400,'أضف الرسالة المطلوبة أو المستندات.');if(['waiting','reviewed'].includes(d.status)&&!d.message)fail(400,'اكتب تفاصيل المعلومات المطلوبة أو خلاصة المراجعة.');
  const docs=await checkDocuments(d.document_ids,r.company_id);const now=timestamp();const message=d.message||(d.status==='reviewing'?'بدأت مراجعة الطلب.':'تم تحديث حالة الطلب.');
  const batch=[stmt('UPDATE legal_requests SET status=?,resolution=CASE WHEN ?=\'reviewed\' THEN ? ELSE resolution END,version=version+1,updated_at=? WHERE id=? AND version=?',d.status,d.status,d.message,now,id,d.version),stmt('INSERT INTO request_events (id,request_id,actor_id,actor_name,from_status,to_status,message,created_at) SELECT ?,?,?,?,?,?,?,? WHERE changes()=1',d.event_id,id,user.userId,admin?'الفريق القانوني':company?.contact_name||user.displayName,r.status,d.status,message,now),...docs.map(doc=>stmt('INSERT OR IGNORE INTO request_documents (request_id,document_id) SELECT ?,? WHERE EXISTS (SELECT 1 FROM request_events WHERE id=?)',id,doc,d.event_id))];const changes=await rawDb().batch(batch);if(!changes[0].meta.changes)fail(409,'تغير الطلب أثناء العمل؛ حدّث الصفحة ثم أعد المحاولة.');return json({ok:true});
 }
 const c=company||await requireCompany(user.userId);
 if(path==='employees'&&method==='POST'){
  const d=employeeRule.parse(await body(req));if(!validDates(d))fail(400,'راجع تاريخ بدء العمل ونهاية العقد.');const id=newId();const now=timestamp();await stmt('INSERT INTO employees (id,company_id,full_name,employee_number,job_title,department,email,start_date,contract_type,contract_end,status,notes,archived,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,0,?,?)',id,c.id,d.full_name,d.employee_number,d.job_title,d.department,d.email,d.start_date,d.contract_type,d.contract_end,d.status,d.notes,now,now).run();return json({id},201);
 }
 if(path.startsWith('employees/')&&method==='PATCH'){
  const id=path.split('/')[1];const e=await first('SELECT * FROM employees WHERE id=? AND company_id=?',id,c.id);if(!e)fail(404,'الموظف غير موجود.');const data=await body(req);
  if(Object.keys(data).length===1&&'archived'in data){const d=z.object({archived:z.number().int().min(0).max(1)}).parse(data);await stmt('UPDATE employees SET archived=?,updated_at=? WHERE id=? AND company_id=?',d.archived,timestamp(),id,c.id).run();return json({id})}
  const d=employeeRule.parse(data);if(!validDates(d))fail(400,'راجع تاريخ بدء العمل ونهاية العقد.');await stmt('UPDATE employees SET full_name=?,employee_number=?,job_title=?,department=?,email=?,start_date=?,contract_type=?,contract_end=?,status=?,notes=?,updated_at=? WHERE id=? AND company_id=?',d.full_name,d.employee_number,d.job_title,d.department,d.email,d.start_date,d.contract_type,d.contract_end,d.status,d.notes,timestamp(),id,c.id).run();return json({id});
 }
 if(path==='documents'&&method==='POST'){
  if(Number(req.headers.get('content-length')||0)>10*1024*1024+100000)fail(413,'حجم الملف يتجاوز 10MB.');const form=await req.formData();const file=form.get('file');if(!(file instanceof File)||!file.size||file.size>10*1024*1024)fail(400,'اختر ملف PDF أو Word بحجم لا يتجاوز 10MB.');
  const ext=file.name.split('.').pop()?.toLowerCase();const types:Record<string,string>={pdf:'application/pdf',doc:'application/msword',docx:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'};if(!ext||!types[ext])fail(400,'الأنواع المسموحة: PDF وDOC وDOCX.');const bytes=await file.arrayBuffer();const b=new Uint8Array(bytes);const signature=ext==='pdf'?new TextDecoder().decode(b.slice(0,5))==='%PDF-':ext==='doc'?b[0]===0xd0&&b[1]===0xcf&&b[2]===0x11&&b[3]===0xe0:b[0]===0x50&&b[1]===0x4b;if(!signature)fail(400,'محتوى الملف لا يطابق نوعه؛ اختر ملفًا صالحًا.');
  const eid=String(form.get('employee_id')||'')||null;if(eid&&!await first('SELECT id FROM employees WHERE id=? AND company_id=?',eid,c.id))fail(403,'الموظف غير متاح.');const id=newId();const key=`${c.id}/${id}.${ext}`;const name=file.name.replace(/[\r\n\x00]/g,'').slice(0,180);const category=eid?'عقد موظف':form.get('category')==='عقد'?'عقد':'مستند';
  await bucket().put(key,bytes,{httpMetadata:{contentType:types[ext]}});try{await stmt('INSERT INTO documents (id,company_id,employee_id,storage_key,name,mime,size,category,uploaded_by,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)',id,c.id,eid,key,name,types[ext],file.size,category,user.userId,timestamp()).run()}catch(e){await bucket().delete(key);throw e}return json({id,company_id:c.id,employee_id:eid,name,mime:types[ext],size:file.size,category,created_at:timestamp()},201);
 }
 if(path==='analyses'&&method==='POST'){
  const d=z.object({id:idRule,scenario:z.enum(['termination','supplier','contract']),title:z.string().trim().max(160).default(''),inputs:z.record(z.string().max(3000)),employee_id:idRule.nullable().optional(),document_ids:fileIds}).parse(await body(req));const existing=await first('SELECT id FROM analyses WHERE id=? AND company_id=?',d.id,c.id);if(existing)return json(existing);
  const docs=await checkDocuments(d.document_ids,c.id);if(d.scenario==='contract'&&!docs.length)fail(400,'أرفق عقدًا لبدء التجربة.');if(d.scenario==='termination'&&!d.inputs.reason?.trim())fail(400,'حدد سبب إنهاء العلاقة.');if(d.scenario==='supplier'&&!d.inputs.scope?.trim())fail(400,'حدد نطاق التوريد.');
  if(d.employee_id){const e=await first('SELECT * FROM employees WHERE id=? AND company_id=?',d.employee_id,c.id);if(!e)fail(404,'الموظف غير موجود.');d.inputs.employee_name=e.full_name;d.inputs.contract_type=e.contract_type;d.inputs.duration=serviceDuration(e.start_date)}
  const result=analysisProvider.analyze(d.scenario,d.inputs,docs.length);const title=d.title||(d.scenario==='contract'?'تحليل عقد توريد':d.scenario==='supplier'?'توقيع عقد مع مورد':`إنهاء علاقة موظف${d.inputs.employee_name?': '+d.inputs.employee_name:''}`);await rawDb().batch([stmt('INSERT INTO analyses (id,company_id,employee_id,kind,scenario,title,inputs_json,result_json,risk,engine,created_by,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)',d.id,c.id,d.employee_id||null,d.scenario==='contract'?'contract':'decision',d.scenario,title,JSON.stringify(d.inputs),JSON.stringify(result),result.risk,'demo-v1',user.userId,timestamp()),...docs.map(id=>stmt('INSERT INTO analysis_documents (analysis_id,document_id) VALUES (?,?)',d.id,id))]);return json({id:d.id},201);
 }
 if(path==='requests'&&method==='POST'){
  const d=reqRule.parse(await body(req));const old=await first('SELECT * FROM legal_requests WHERE id=? AND company_id=?',d.id,c.id);if(old)return json(old);let ids=d.document_ids;
  if(d.analysis_id){if(!await first('SELECT id FROM analyses WHERE id=? AND company_id=?',d.analysis_id,c.id))fail(404,'التحليل غير موجود.');ids=[...new Set([...ids,...(await rows('SELECT document_id FROM analysis_documents WHERE analysis_id=?',d.analysis_id)).map((a:any)=>a.document_id)])]}
  const docs=await checkDocuments(ids,c.id);const now=timestamp();await rawDb().batch([stmt('INSERT INTO legal_requests (id,company_id,analysis_id,type,description,urgency,status,resolution,version,created_by,created_at,updated_at) VALUES (?,?,?,?,?,?,\'new\',\'\',0,?,?,?)',d.id,c.id,d.analysis_id||null,d.type,d.description,d.urgency,user.userId,now,now),stmt('INSERT INTO request_events (id,request_id,actor_id,actor_name,from_status,to_status,message,created_at) VALUES (?,?,?,?,?,?,?,?)',newId(),d.id,user.userId,c.contact_name,'','new','تم استلام الطلب وإحالته لقائمة المراجعة.',now),...docs.map(id=>stmt('INSERT INTO request_documents (request_id,document_id) VALUES (?,?)',d.id,id))]);return json(await first('SELECT * FROM legal_requests WHERE id=?',d.id),201);
 }
 fail(404,'المسار غير موجود.');
 }catch(e){if(e instanceof ApiError)return json({error:e.message},e.status);if(e instanceof z.ZodError)return json({error:'راجع الحقول المطلوبة وصحة البيانات.',fields:e.flatten().fieldErrors},400);const message=e instanceof Error?e.message:'';if(message.includes('UNIQUE constraint failed'))return json({error:'هذه البيانات موجودة مسبقًا. راجع الرقم الوظيفي أو حدّث الصفحة.'},409);console.error('Mirsad operation failed',e instanceof Error?e.name:'UnknownError',message.slice(0,180));return json({error:'تعذر إكمال العملية الآن. بيانات النموذج باقية؛ أعد المحاولة.'},503)}}
function validDates(d:z.infer<typeof employeeRule>){const start=new Date(d.start_date+'T00:00:00Z');if(isNaN(start.valueOf())||start.toISOString().slice(0,10)!==d.start_date||d.start_date>timestamp().slice(0,10))return false;if(d.contract_end){const end=new Date(d.contract_end+'T00:00:00Z');if(isNaN(end.valueOf())||end.toISOString().slice(0,10)!==d.contract_end||d.contract_end<d.start_date)return false}return true}
